#!/bin/sh

JAVA_HOME=${JAVA_HOME:-/usr/lib/jvm/java-8-oracle/}

# If you get the error :
## javax.net.ssl.SSLHandshakeException:
## sun.security.validator.ValidatorException: PKIX path building failed:
## sun.security.provider.certpath.SunCertPathBuilderException:
## unable to find valid certification path to requested target

## Then you must add your webserver's certificate to the global cacerts file
## of the client's JVM

## This script does that.

# This import the CAcert part of your p12, It needs a pem with the cacert, you can extract it from your p12 as follows
# openssl pkcs12 -nokeys -cacerts -in my.p12  -out my-cert.pem
# sudo keytool -import -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass changeit -alias ejbca -trustcacerts -file superadmin-cert.pem

# This is just inserting a given cert, you have to extract it yourself
# go with a browser to your URL, go to settings, (probably 'advanced') then into certificates (or 'manage certificate'), take a look at the certificated fed to yoru browser and chose 'export', rename it ws-login.cert
#sudo keytool -import -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass changeit -alias ejbca-browser-cert -trustcacerts -file ws-login.cert

## WSDL itself from a file maybe?

## maybe is the provided truststorejks we shoudl import?
# this exports from it
# keytool -export -alias managementca -file ejbca-server.cert -keystore truststore.jks 
# we import into cacerts using
sudo keytool -import -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass changeit -alias ejbca-server-cert -trustcacerts -file ejbca-server.cert





